$ProjectDir = $PSScriptRoot
$snapshotFile = Join-Path $ProjectDir "changelog_snapshot.json"
$outputFile = Join-Path $ProjectDir "Classes\Mods\ChangelogEntries.g.cs"
$customBuildMarker = Join-Path $ProjectDir ".custom-build"
$excludePattern = '(\\bin\\|\\obj\\|\\References\\|ChangelogEntries\.g\.cs$|PluginInfo\.cs$)'
$scriptSchemaVersion = 8

$currentVersion = ""
$pluginInfoFile = Join-Path $ProjectDir "PluginInfo.cs"
if (Test-Path $pluginInfoFile) {
    $pluginContent = Get-Content $pluginInfoFile -Raw
    $versionMatch = [regex]::Match($pluginContent, 'Version\s*=\s*"([^"]+)"')
    if ($versionMatch.Success) { $currentVersion = $versionMatch.Groups[1].Value }
}

if (Test-Path $customBuildMarker) {
    @"
// Auto-generated by GenerateChangelog.ps1 - do not edit
namespace Seralyth.Classes.Mods
{
    public static class AutoChangelogEntries
    {
        public static void Populate()
        {
        }
    }
}
"@ | Out-File $outputFile -Encoding UTF8
    exit
}

function Get-ButtonBlockHash($content, $start) {
    $braceDepth = 0
    $inString = $false
    $skipNext = $false
    for ($i = $start; $i -lt $content.Length; $i++) {
        if ($skipNext) { $skipNext = $false; continue }
        $c = $content[$i]
        if ($inString) {
            if ($c -eq '"') {
                if ($i -gt 0 -and $content[$i - 1] -eq '\') { continue }
                if ($i + 1 -lt $content.Length -and $content[$i + 1] -eq '"') { $skipNext = $true; continue }
                $inString = $false
            }
        } else {
            if ($c -eq '"' -or ($c -eq "'")) {
                $inString = $true
            } elseif ($c -eq '{') {
                $braceDepth++
            } elseif ($c -eq '}') {
                $braceDepth--
                if ($braceDepth -eq 0) {
                    $block = $content.Substring($start, $i - $start + 1)
                    $block = $block -replace "`r", '' -replace '\s+', ' '
                    $bytes = [Text.Encoding]::UTF8.GetBytes($block)
                    $hashBytes = (New-Object Security.Cryptography.MD5CryptoServiceProvider).ComputeHash($bytes)
                    return [System.BitConverter]::ToString($hashBytes)
                }
            }
        }
    }
    return ""
}

function Get-ButtonBlockEnd($content, $start) {
    $braceDepth = 0
    $inString = $false
    $skipNext = $false
    for ($i = $start; $i -lt $content.Length; $i++) {
        if ($skipNext) { $skipNext = $false; continue }
        $c = $content[$i]
        if ($inString) {
            if ($c -eq '"') {
                if ($i -gt 0 -and $content[$i - 1] -eq '\') { continue }
                if ($i + 1 -lt $content.Length -and $content[$i + 1] -eq '"') { $skipNext = $true; continue }
                $inString = $false
            }
        } else {
            if ($c -eq '"' -or ($c -eq "'")) {
                $inString = $true
            } elseif ($c -eq '{') {
                $braceDepth++
            } elseif ($c -eq '}') {
                $braceDepth--
                if ($braceDepth -eq 0) { return $i }
            }
        }
    }
    return $content.Length - 1
}

function Decode-CSharpString($s) {
    $sb = New-Object Text.StringBuilder
    for ($i = 0; $i -lt $s.Length; $i++) {
        if ($s[$i] -eq '\' -and $i + 1 -lt $s.Length) {
            $next = $s[$i + 1]
            switch ($next) {
                '"' { [void]$sb.Append('"'); $i++ }
                '\' { [void]$sb.Append('\'); $i++ }
                'n' { [void]$sb.Append("`n"); $i++ }
                'r' { [void]$sb.Append("`r"); $i++ }
                't' { [void]$sb.Append("`t"); $i++ }
                '0' { [void]$sb.Append("`0"); $i++ }
                default { [void]$sb.Append($s[$i]) }
            }
        } else {
            [void]$sb.Append($s[$i])
        }
    }
    return $sb.ToString()
}

function Get-ButtonInfos($content) {
    $seen = @{}
    $unique = @()
    $blockPattern = 'new\s+ButtonInfo\s*\{'
    $blockMatches = [regex]::Matches($content, $blockPattern)
    for ($i = $blockMatches.Count - 1; $i -ge 0; $i--) {
        $start = $blockMatches[$i].Index
        $end = Get-ButtonBlockEnd $content $start
        $block = $content.Substring($start, $end - $start + 1)
        $bHash = Get-ButtonBlockHash $content $start
        $textMatch = [regex]::Match($block, 'buttonText\s*=\s*"((?:[^"\\]|\\.)*)"')
        $overlapMatch = [regex]::Match($block, 'overlapText\s*=\s*"((?:[^"\\]|\\.)*)"')
        $tipMatch = [regex]::Match($block, '(?i)tooltip\s*=\s*\$?"((?:[^"\\]|\\.)*)"')
        $text = if ($textMatch.Success) { Decode-CSharpString $textMatch.Groups[1].Value } else { "" }
        $overlap = if ($overlapMatch.Success) { Decode-CSharpString $overlapMatch.Groups[1].Value } else { "" }
        if ($overlap) { $text = $overlap }
        $tip = if ($tipMatch.Success) { Decode-CSharpString $tipMatch.Groups[1].Value } else { "" }
        if ($text -and -not $seen.ContainsKey($text)) {
            $seen[$text] = $true
            $unique = @(@{ text = $text; tooltip = $tip; hash = $bHash }) + $unique
        }
    }
    return $unique
}

function Get-FileDesc($p) {
    return [System.IO.Path]::GetFileNameWithoutExtension($p)
}

function Is-ButtonsFile($p) {
    $name = [System.IO.Path]::GetFileNameWithoutExtension($p)
    return $name -eq 'Buttons'
}

function Filter-ModButtons($infos) {
    return $infos | Where-Object { $_.text -notmatch '^(Exit |Disable |Hide |Swap |Info |Reset |Notification|Streamer|Global|Narrate|Chain|Toggle|Open|Return|Search|Settings|Menu\s|Enable|Disconnect|Conduct|Keybind|Rebind|Plugin|Soundboard|Friend|Room|Safety|Movement|Advantage|Visual|Fun|Overpowered|Detected|Projectile|Master|Favorite|Experimental|Credits|Letter\s|Update\s|Favorite\s|Main|Checkbox|Joystick\s|Physical\s|Bark\s|Wrist\s|Watch\s|Shiny\s|Transparent\s|Crystallize\s|Explode\s|Thick\s|Long\s|Flip\s|Round\s|Outline\s|Strikethrough\s|Underline\s|Small-Caps\s|Redact\s|Inner\s|Smooth\s|Freeze\s|Zero\s|Menu\s|Alphabetize\s|Custom\s|Particle\s|Gradient\s|Animated\s|Voice\s|AI\s|Debug\s|Slow\s|Average\s|Frametime\s|Legacy\s|Advanced\s|Flip\s|Narrate\s|Conduct\s|Stack\s|Hide\s|Rapid\s|Vibrant\s|Gripless\s|Triggerless\s|Hard\s|Small\s|Smooth\s|Swap\s|Gun\s|Incremental\s|Page\s|Exclusive\s|Dynamic\s|Horizontal\s|Scrolling\s|Checkbox\s|Serversided\s|Clear\s|Favorite\s|Room|Overflow|Uppercase|Lowercase|Annoying|Click\s|Join\s|Swap\s|PC\s|Disable\s|No\s|Info\s|Conduct\s|Slow\s|Average\s|Frametime\s)' }
}

function Escape-CSharp($s) {
    $s = $s -replace '\\', '\\\\'
    $s = $s -replace '"', '\"'
    $s = $s -replace "`r", '\r'
    $s = $s -replace "`n", '\n'
    $s = $s -replace "`t", '\t'
    return $s
}

function Strip-RichText($s) {
    return $s -replace '<[^>]+>', ''
}

function Get-Desc($infos, $fallback) {
    if ($infos.Count -gt 0 -and $infos.Count -le 5) {
        return ($infos | ForEach-Object { Strip-RichText $_.text }) -join ', '
    }
    if ($infos.Count -gt 5) {
        return "$(Strip-RichText $infos[0].text) and $($infos.Count - 1) more"
    }
    return $fallback
}

$currentFiles = @{}
Get-ChildItem -Path $ProjectDir -Filter "*.cs" -Recurse | Where-Object { $_.FullName -notmatch $excludePattern } | ForEach-Object {
    $rel = $_.FullName.Substring($ProjectDir.Length).TrimStart('\')
    $hash = (Get-FileHash -Path $_.FullName -Algorithm MD5).Hash
    $content = Get-Content $_.FullName -Raw
    $infos = Get-ButtonInfos $content
    $currentFiles[$rel] = @{ hash = $hash; infos = $infos }
}

$storedVersion = ""
$storedEntries = @()
$prevFiles = @{}
$hasSnapshot = $false
if (Test-Path $snapshotFile) {
    try {
        $json = Get-Content $snapshotFile -Raw | ConvertFrom-Json
        $storedSchema = if ($json._schema) { [int]$json._schema } else { 0 }
        if ($json._version) { $storedVersion = $json._version }
        if ($storedSchema -eq $scriptSchemaVersion) {
            if ($json._entries) { $storedEntries = @($json._entries) | ForEach-Object { @{ type = $_.type; desc = Strip-RichText $_.desc } } }
        }
        $hasSnapshot = $true
        foreach ($entry in $json.PSObject.Properties) {
            if ($entry.Name -match '^_') { continue }
            $val = $entry.Value
            if ($val -is [PSCustomObject] -and $val.hash) {
                if ($val.infos) {
                    $infosList = @($val.infos) | ForEach-Object { @{ text = $_.text; tooltip = if ($_.tooltip) { $_.tooltip } else { "" }; hash = if ($_.hash) { $_.hash } else { "" } } }
                } elseif ($val.buttons) {
                    $oldBtns = @($val.buttons)
                    $oldTips = if ($val.tooltips) { @($val.tooltips) } else { @() }
                    $infosList = @()
                    for ($bi = 0; $bi -lt $oldBtns.Count; $bi++) {
                        $infosList += @{ text = $oldBtns[$bi]; tooltip = if ($bi -lt $oldTips.Count) { $oldTips[$bi] } else { "" }; hash = "" }
                    }
                } else { $infosList = @() }
                $prevFiles[$entry.Name] = @{ hash = $val.hash; infos = $infosList }
            } elseif ($val -is [string]) {
                $prevFiles[$entry.Name] = @{ hash = $val; infos = @() }
            }
        }
    } catch {}
}

if ($hasSnapshot -and $storedVersion -ne $currentVersion -and $currentVersion -ne "") {
    $snap = @{ _schema = $scriptSchemaVersion; _version = $currentVersion }
    foreach ($kv in $currentFiles.GetEnumerator()) {
        $snap[$kv.Key] = @{ hash = $kv.Value.hash; infos = $kv.Value.infos }
    }
    $snap | ConvertTo-Json -Depth 5 | Out-File $snapshotFile -Encoding UTF8
    @"
// Auto-generated by GenerateChangelog.ps1 - do not edit
namespace Seralyth.Classes.Mods
{
    public static class AutoChangelogEntries
    {
        public static void Populate()
        {
        }
    }
}
"@ | Out-File $outputFile -Encoding UTF8
    exit
}

$newDiff = @()
if ($hasSnapshot) {
    $addedFiles = @()
    foreach ($kv in $currentFiles.GetEnumerator()) {
        if (-not $prevFiles.ContainsKey($kv.Key)) { $addedFiles += $kv.Key }
    }

    $removedFiles = @()
    foreach ($k in $prevFiles.Keys) {
        if (-not $currentFiles.ContainsKey($k)) { $removedFiles += $k }
    }

    $processedRemove = @{}
    $processedAdd = @{}
    $renameMap = @{}
    foreach ($rf in $removedFiles) {
        $hash = $prevFiles[$rf].hash
        $match = $null
        foreach ($af in $addedFiles) {
            if (-not $processedAdd.ContainsKey($af) -and $currentFiles[$af].hash -eq $hash) {
                $match = $af
                break
            }
        }
        if ($match) {
            $processedRemove[$rf] = $true
            $processedAdd[$match] = $true
            $renameMap[$rf] = $match
        }
    }

    foreach ($f in ($addedFiles | Sort-Object)) {
        if ($processedAdd.ContainsKey($f)) { continue }
        $isB = Is-ButtonsFile $f
        if ($isB) {
            $filtered = Filter-ModButtons $currentFiles[$f].infos
            foreach ($b in $filtered) { $newDiff += @{ type = "ADDED"; desc = Strip-RichText $b.text } }
        } else {
            $desc = Get-Desc $currentFiles[$f].infos (Get-FileDesc $f)
            $newDiff += @{ type = "ADDED"; desc = $desc }
        }
    }

    foreach ($f in ($removedFiles | Sort-Object)) {
        if ($processedRemove.ContainsKey($f)) { continue }
        $isB = Is-ButtonsFile $f
        if ($isB) {
            $filtered = Filter-ModButtons $prevFiles[$f].infos
            foreach ($b in $filtered) { $newDiff += @{ type = "REMOVED"; desc = Strip-RichText $b.text } }
        } else {
            $desc = Get-Desc $prevFiles[$f].infos (Get-FileDesc $f)
            $newDiff += @{ type = "REMOVED"; desc = $desc }
        }
    }

    $updatedFiles = @()
    foreach ($kv in $currentFiles.GetEnumerator()) {
        if ($prevFiles.ContainsKey($kv.Key) -and $prevFiles[$kv.Key].hash -ne $kv.Value.hash) {
            $updatedFiles += $kv.Key
        }
    }

    foreach ($f in ($updatedFiles | Sort-Object)) {
        $isB = Is-ButtonsFile $f
        if ($isB) {
            $oldFiltered = Filter-ModButtons $prevFiles[$f].infos
            $newFiltered = Filter-ModButtons $currentFiles[$f].infos

            $oldTextSet = @{}
            foreach ($b in $oldFiltered) { $oldTextSet[$b.text] = $b }
            $newTextSet = @{}
            foreach ($b in $newFiltered) { $newTextSet[$b.text] = $b }

            $processedOld = @{}
            $processedNew = @{}

            $max = [Math]::Max($oldFiltered.Count, $newFiltered.Count)
            for ($i = 0; $i -lt $max; $i++) {
                $oldB = if ($i -lt $oldFiltered.Count) { $oldFiltered[$i] } else { $null }
                $newB = if ($i -lt $newFiltered.Count) { $newFiltered[$i] } else { $null }

                if ($oldB -and $newB) {
                    if ($oldB.text -eq $newB.text) {
                        $processedOld[$oldB.text] = $true
                        $processedNew[$newB.text] = $true
                        if ($oldB.tooltip -ne $newB.tooltip) {
                            $newDiff += @{ type = "UPDATED"; desc = "$(Strip-RichText $oldB.text) tooltip" }
                        } elseif ($oldB.hash -ne "" -and $newB.hash -ne "" -and $oldB.hash -ne $newB.hash) {
                            $newDiff += @{ type = "UPDATED"; desc = Strip-RichText $oldB.text }
                        }
                    } elseif (-not $oldTextSet.ContainsKey($newB.text) -and -not $newTextSet.ContainsKey($oldB.text)) {
                        $newDiff += @{ type = "RENAMED"; desc = "$(Strip-RichText $oldB.text) to $(Strip-RichText $newB.text)" }
                        $processedOld[$oldB.text] = $true
                        $processedNew[$newB.text] = $true
                    }
                }
            }

            $unmatchedOld = @()
            $unmatchedNew = @()
            foreach ($b in $oldFiltered) {
                if (-not $processedOld.ContainsKey($b.text) -and -not $newTextSet.ContainsKey($b.text)) {
                    $unmatchedOld += $b
                }
            }
            foreach ($b in $newFiltered) {
                if (-not $processedNew.ContainsKey($b.text) -and -not $oldTextSet.ContainsKey($b.text)) {
                    $unmatchedNew += $b
                }
            }
            if ($unmatchedOld.Count -eq 1 -and $unmatchedNew.Count -eq 1) {
                $uo = $unmatchedOld[0]
                $un = $unmatchedNew[0]
                $uoPos = [array]::IndexOf($oldFiltered, $uo)
                $unPos = [array]::IndexOf($newFiltered, $un)
                $posDist = [Math]::Abs($uoPos - $unPos)
                if ($posDist -le 2) {
                    $newDiff += @{ type = "RENAMED"; desc = "$(Strip-RichText $uo.text) to $(Strip-RichText $un.text)" }
                    $processedOld[$uo.text] = $true
                    $processedNew[$un.text] = $true
                }
            }

            foreach ($b in $oldFiltered) {
                if (-not $processedOld.ContainsKey($b.text)) {
                    if ($newTextSet.ContainsKey($b.text)) {
                        $nb = $newTextSet[$b.text]
                        if ($b.tooltip -ne $nb.tooltip) {
                            $newDiff += @{ type = "UPDATED"; desc = "$(Strip-RichText $b.text) tooltip" }
                        } elseif ($b.hash -ne "" -and $nb.hash -ne "" -and $b.hash -ne $nb.hash) {
                            $newDiff += @{ type = "UPDATED"; desc = Strip-RichText $b.text }
                        }
                    } else {
                        $newDiff += @{ type = "REMOVED"; desc = Strip-RichText $b.text }
                    }
                }
            }
            foreach ($b in $newFiltered) {
                if (-not $processedNew.ContainsKey($b.text) -and -not $oldTextSet.ContainsKey($b.text)) {
                    $newDiff += @{ type = "ADDED"; desc = Strip-RichText $b.text }
                }
            }
        } else {
            $desc = Get-Desc $currentFiles[$f].infos (Get-FileDesc $f)
            $newDiff += @{ type = "UPDATED"; desc = $desc }
        }
    }
}

$merged = @{}
foreach ($e in $storedEntries) {
    $key = "$($e.type)|$($e.desc)"
    $merged[$key] = $e
}
foreach ($e in $newDiff) {
    $key = "$($e.type)|$($e.desc)"
    $merged[$key] = $e
}
$allEntries = $merged.Values

$lines = @()
$lines += "// Auto-generated by GenerateChangelog.ps1 - do not edit"
$lines += "namespace Seralyth.Classes.Mods"
$lines += "{"
$lines += "    public static class AutoChangelogEntries"
$lines += "    {"
$lines += "        public static void Populate()"
$lines += "        {"
foreach ($e in $allEntries) {
    $lines += "            Changelog.Add(""$(Escape-CSharp $e.type)"", ""$(Escape-CSharp $e.desc)"");"
}

$lines += "        }"
$lines += "    }"
$lines += "}"
$lines -join "`r`n" | Out-File $outputFile -Encoding UTF8

$snap = @{ _schema = $scriptSchemaVersion; _version = $currentVersion; _entries = @($allEntries) }
foreach ($kv in $currentFiles.GetEnumerator()) {
    $snap[$kv.Key] = @{ hash = $kv.Value.hash; infos = $kv.Value.infos }
}
$snap | ConvertTo-Json -Depth 5 | Out-File $snapshotFile -Encoding UTF8
