// Auto-generated by GenerateChangelog.ps1 - do not edit
namespace Seralyth.Classes.Mods
{
    public static class AutoChangelogEntries
    {
        public static void Populate()
        {
            Changelog.Add("ADDED", "Forsaken");
            Changelog.Add("UPDATED", "CoolMods");
            Changelog.Add("ADDED", "Change Category Display [Next to FPS]");
            Changelog.Add("UPDATED", "Click on an emoji you'd like to use!");
            Changelog.Add("UPDATED", "Exit Friends and 18 more");
            Changelog.Add("RENAMED", "Events to Console Assets");
            Changelog.Add("UPDATED", "Achievements tooltip");
            Changelog.Add("UPDATED", "Admin Mods, Console Assets, Exit Mod Checker, No mods detected");
            Changelog.Add("UPDATED", "Admin Mods, Exit Mod Checker, No mods detected");
            Changelog.Add("REMOVED", "");
            Changelog.Add("UPDATED", "Projectiles");
            Changelog.Add("UPDATED", "NetworkSearchDisplay");
            Changelog.Add("UPDATED", "Exit Quests and 6 more");
            Changelog.Add("UPDATED", "Safety");
            Changelog.Add("UPDATED", "Exit Achievements, You have no achievements.");
            Changelog.Add("UPDATED", "NetworkMenuDisplay");
            Changelog.Add("ADDED", "Change GunLib Shape [Disabled]");
            Changelog.Add("UPDATED", "Exit Friends and 20 more");
            Changelog.Add("UPDATED", "Quest Mods");
            Changelog.Add("UPDATED", "GunLib Fling Gun V2");
            Changelog.Add("UPDATED", "Exit Macros and 24 more");
            Changelog.Add("ADDED", "NetworkSearchDisplay");
            Changelog.Add("REMOVED", "Change Fade Theme [Green]");
            Changelog.Add("ADDED", "GunLib Trail");
            Changelog.Add("ADDED", "GunLib Fling Gun V2");
            Changelog.Add("REMOVED", "Console Assets");
            Changelog.Add("UPDATED", "GunLib");
            Changelog.Add("ADDED", "Change Fade Theme [Green]");
            Changelog.Add("ADDED", "GunLib Line");
            Changelog.Add("UPDATED", "Exit Info Screen and 55 more");
            Changelog.Add("UPDATED", "Exit Quests and 5 more");
            Changelog.Add("UPDATED", "GunLib Fling Gun V2 tooltip");
            Changelog.Add("UPDATED", "Experimental");
            Changelog.Add("UPDATED", "Exit Quests and 12 more");
            Changelog.Add("ADDED", "GunLib Fling Gun");
            Changelog.Add("UPDATED", "Change Fade Theme [Green] tooltip");
            Changelog.Add("UPDATED", "GunLib Fling Gun tooltip");
            Changelog.Add("UPDATED", "NetworkMenuManager");
            Changelog.Add("UPDATED", "Exit Mod List, Exit Building Block Browser, Exit Cosmetic Browser, Previous Page, Next Page");
        }
    }
}
